cc_binary(
    name = "css_munge",
    srcs = ["css_munge.cc"],
    deps = [
        "@com_github_open_source_parsers_jsoncpp//:json",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/log:flags",
        "@com_google_absl//absl/log:initialize",
        "@com_google_absl//absl/log:log",
    ],
    visibility = ["//visibility:public"],
)
