cc_binary(
    name = "libcurl_demo",
    srcs = ["libcurl_demo.cc"],
    args = ["--alsologtostderr"],
    deps = [
        "@com_google_absl//absl/cleanup",
        "@com_google_absl//absl/strings",
        "@com_github_curl_curl//:curl",
    ],
)

