cc_binary(
    name = "libcurl_demo",
    srcs = ["libcurl_demo.cc"],
    args = ["--alsologtostderr"],
    deps = [
        "@com_google_absl//absl/cleanup",
        "@com_google_absl//absl/strings",
        "@com_github_curl_curl//:curl",
        #"@com_github_enki_libev//:libev",
        #"@com_github_gflags_gflags//:gflags",
        #"@com_github_glog_glog//:glog",
        #"@com_gitlab_gnutls//:gnutls",
        #"@com_gitlab_libidn_libidn2//:libidn2",
        #"@org_gnu_microhttpd//:microhttpd",
        #"@se_liu_lysator_nettle_nettle//:nettle",
        #"@zlib//:zlib",
    ],
)

